YT_SUBSCRIPTIONS:
  - CHANNEL: "@engineerprompt"
    MAX_SUB_VIDEOS: 3

COLLECT_SORT_MODES: ["top"]
MAX_COMMENTS_PER_VIDEO: 50
MAX_COMMENT_THREAD_DEPTH: 5
MAX_RETRY_SCRAPE: 3
CAPTURE_ARTIFACTS_ON_ERROR: true
ON_VIDEO_FAILURE: "skip"

TRANSCRIPTS_ENABLE: false

API_JITTER_MS_MIN: 250
API_JITTER_MS_MAX: 900

EMBEDDINGS_ENABLE: false
LLM_PROVIDER:
TM_CLUSTERING: "nlp"
